### ISSUE TITLE
Request: Unlimited recommendations

### ISSUE THREAD

**Issue by mtlynch** [Dainius14/twinder#2]
Currently, it seems like Twinder fetches recommendations in batches of 11. The user can go through them, but then when they reach the end, the window closes, and they have to hit "Recommendations" again, then wait for a new fetch to complete.

A nice feature would be for Twinder to fetch new recommendations in the background as they're reaching the end of the batch so that they don't have to close the window and start over or wait for a batch fetch to complete.

**Comment by Dainius14** [comment]
AFAIK once you get a batch of recommendations, you can only like/pass those that are in the batch. When you ask Tinder for a new batch, the old ones return you a "Not authorized" error.

Though I can't guarantee this is true. I haven't looked into what API calls the original client makes yet, I plan to do that in the next half of the month.

The reason why every time the window gets closed and you're stopped from interacting while pics are being downloaded, is because files are being managed directly and anything you do matches/recommendations mind end up disturbing the flow of the program aka I'm not ready to deal with all this stuff yet.
